### ISSUE TITLE
How can I use the script as a web server?

### ISSUE THREAD

**Issue by yzqiang** [TheArkive/Socket_Ahkv2#4]
The G33kDude Socket.ahk version can be used as a web server.
But I don't know how to use this version as a web server.
Is there something missed?
I need a AHK V2 web server very much.
Thanks.

**Comment by TheArkive** [comment]
This script is the foundation for what you are calling a "web server".  G33kDude made this HTML separate layer, and it is a separate script.  I have not yet converted his web server to v2.  And honestly I don't know that I will.  It could happen, but I can't make any promises.
